apiVersion: v1
kind: Secret
metadata:
  name: sc-donation-processor-secret
  namespace: solidarity-connection-namespace
type: Opaque
stringData:
  RabbitMQ__Username: "guest"
  RabbitMQ__Password: "guest"
