<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-EventProcessor-444cc24c-3538-489d-a4a1-a35ca0f53313</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="prometheus-net" Version="8.2.1" />
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="prometheus-net.DotNetRuntime" Version="4.4.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.10.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SCDonationProcessor.Application\SCDonationProcessor.Application.csproj" />
    <ProjectReference Include="..\SCDonationProcessor.Infrastructure\SCDonationProcessor.Infrastructure.csproj" />
  </ItemGroup>

</Project>